apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-scraping-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-scraping-deployment
  minReplicas: 5       # Minimum number of replicas
  maxReplicas: 25      # Maximum number of replicas
  targetCPUUtilizationPercentage: 50  # Target CPU utilization percentage
