apiVersion: v1
kind: PersistentVolume
metadata:
  name: scraping-data-pv
  namespace: web-scrapping
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/scraping-data
