apiVersion: v1
kind: Service
metadata:
  name: web-scraping-service
  namespace: web-scrapping
spec:
  selector:
    app: web-scraping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
