apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-scraping-statefulset
  namespace: web-scrapping
spec:
  serviceName: web-scraping-service
  replicas: 10
  selector:
    matchLabels:
      app: web-scraping
  template:
    metadata:
      labels:
        app: web-scraping
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - web-scraping
              topologyKey: kubernetes.io/hostname
      containers:
      - name: web-scraping-container
        image: nginx:latest
        volumeMounts:
        - name: data-volume
          mountPath: /data
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "64Mi"
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
